### ISSUE TITLE
Support react 18 and server components

### ISSUE THREAD

**Issue by fnebenfuehr** [treely/boemly#102]
Here is my fork upgrading chakra to v2.
https://github.com/F1ow/boemly

WIP summary:
- Component build is working
- All test are passing
- Running storybook is not working:  
`Can't import the named export 'Children' from non EcmaScript module (only default export is available)
node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs` --> https://github.com/framer/motion/issues/1525
- Using the boemly with shopify/hydrogen (server components) still not working.

Maybe helpful:
This guide might be helpful because remix uses server components too: https://chakra-ui.com/getting-started/remix-guide

Environment:
os: `macOS 12.4`
node: `v16.15.1` also tried `v17`
npm: `8.11.0`

**Comment by lukasbals** [comment]
Hi @fnebenfuehr ! Thanks for submitting this issue.

We plan to upgrade Boemly to Chakra@v2 as soon as possible. Chakr@v2 does only support React@v18 and higher which is "blocking" us from upgrading currently - we will first migrate our projects to React@v18.

**Comment by lukasbals** [comment]
https://github.com/treely/boemly/pull/132

PR to explicitly only allow React v17.
